version: '3.2'

services:
  clientinformation:
    image: clientinformation:1.0.13
    container_name: 'clientinformation'
    ports:
      - "443:443"
    volumes:
      - "./Volumes/Configuration:/Workspace/Configuration"
